war:
   preparing time: 300
   battle time: 600
   delay message time after server restart: 60
   re-preparing time after server restart: 120
   
territory:
   minDistance: 128
   minDistanceFriendly: 64
   beaconBreakTime: 10
   ironDoorBreakTime: 45
   allowbuildterritoryinotherdim: false
   